name: 'Install Poetry'
description: 'Configure and install poetry, then use it to install dependencies.'
inputs:
  cache-name:
    description: 'A unique name to add to the cache, defaults to none'
    required: false
    default: ''
  python-version:
    description: 'The python version to use, defaults to the latest python available.'
    required: false
    default: '^3'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: set PY env var
      run: echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
    - name: Install Poetry
      run: |
        pip install --upgrade pip
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - name: Add Poetry to Path
      run: echo "::add-path::$HOME/.poetry/bin"
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
    - name: Cache Poetry virtualenv
      uses: actions/cache@v2.0.0
      id: cache-poetry
      with:
        path: ~/.virtualenvs
        key: poetry|${{ inputs.cache-name }}|${{ runner.os }}|${{ env.PY }}|${{ hashFiles('poetry.lock') }}
    - name: Install Project Dependencies (Poetry)
      run: poetry install -vvv
      if: steps.cache-poetry.outputs.cache-hit != 'true'
    - name: Add poetry env to PATH
      run: |
        echo "::add-path::$( poetry env info --path )/bin"
